on: workflow_dispatch

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: |
            cd ./post-actions
            npm i --location=global @vercel/ncc 
            npm run build
      - run: |
            cd ./post-actions
            node ./dist/index.js
      - run: |
         git config --global user.name "Autobot"
         git config --global user.email "autobot@float.financial"
         git rm -rf post-actions
         git add .
         git commit -m "Modified repo"
         git push
